### ISSUE TITLE
Zwave2Mqtt MQTT autodiscovery

### ISSUE THREAD

**Issue by robertsLando** [hassio-addons/addon-zwave2mqtt#6]
I have just published on [Zwave2Mqtt](https://github.com/OpenZWave/Zwave2Mqtt) master a first beta version with MQTT discovery. I'm looking for testers

**Comment by frenck** [comment]
Nice @robertsLando! 🎖 

Although, I currently have an issue with building the project at all.

```
make: Leaving directory '/opt/node_modules/@serialport/bindings/build'

> openzwave-shared@1.5.1 install /opt/node_modules/openzwave-shared
> node-gyp rebuild

Illegal option -p
nm: 'a.out': No such file
gyp: Call to 'ldconfig -p | grep 'libopenzwave.so ' | awk '{print $4}' | xargs nm -g --demangle |grep OpenZWave::Value::GetTypeNameFromEnum | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/node_modules/openzwave-shared
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by robertsLando** [comment]
Tomorrow I will release version 2.0 beta with lot of fixes

Daniel

**Comment by robertsLando** [comment]
Out now https://github.com/OpenZWave/Zwave2Mqtt/releases/tag/v2.0.0

**Comment by frenck** [comment]
🎉 
Pushed the upgrade onto our edge. Currently building and will be available on our edge repos shortly for testing. 

Thanks @robertsLando 👍

**Comment by robertsLando** [comment]
Thanks!! 

Daniel
